#!/usr/bin/env bash

# Brief: REDIS console
# Usage: ./redis-cli -h

. "${BASH_SOURCE%/*}/redis.bash"

trap 'redis_disconnect ; echo' exit
trap 'exit' HUP TERM INT QUIT

redis_connect "${@}" || exit 1

history -c # Clear Bash history

while :;do
  read -e -p "${REDIS_HOST}:${REDIS_PORT}_${REDIS_DB:-0}$ "
  [[ "${REPLY^^}" = @(QUIT|EXIT|Q) ]] && break

  redis_exec "${REPLY}"
  (($?==22)) && exit 22

  history -s "${REPLY}" # Append latest command to Bash history
done
